// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherApp.DataAccessLayer;

namespace WeatherService.Migrations
{
    [DbContext(typeof(WeatherContext))]
    partial class WeatherContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WeatherApp.Domain.Clouds", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cloudiness")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Clouds");
                });

            modelBuilder.Entity("WeatherApp.Domain.Coordinates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("lat")
                        .HasColumnType("float");

                    b.Property<double>("lon")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Coordinates");
                });

            modelBuilder.Entity("WeatherApp.Domain.Main", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("feels_like")
                        .HasColumnType("float");

                    b.Property<int>("humidity")
                        .HasColumnType("int");

                    b.Property<int>("pressure")
                        .HasColumnType("int");

                    b.Property<double>("temp")
                        .HasColumnType("float");

                    b.Property<double>("temp_max")
                        .HasColumnType("float");

                    b.Property<double>("temp_min")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Mains");
                });

            modelBuilder.Entity("WeatherApp.Domain.Root", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("city_Id")
                        .HasColumnType("int");

                    b.Property<string>("cityname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("cloudsId")
                        .HasColumnType("int");

                    b.Property<int?>("coordinatesId")
                        .HasColumnType("int");

                    b.Property<int?>("mainId")
                        .HasColumnType("int");

                    b.Property<int?>("systemId")
                        .HasColumnType("int");

                    b.Property<int>("timezone")
                        .HasColumnType("int");

                    b.Property<int>("update_time")
                        .HasColumnType("int");

                    b.Property<int>("visibility")
                        .HasColumnType("int");

                    b.Property<int?>("windId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("cloudsId");

                    b.HasIndex("coordinatesId");

                    b.HasIndex("mainId");

                    b.HasIndex("systemId");

                    b.HasIndex("windId");

                    b.ToTable("Roots");
                });

            modelBuilder.Entity("WeatherApp.Domain.System", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("internal_parameter")
                        .HasColumnType("int");

                    b.Property<double>("message")
                        .HasColumnType("float");

                    b.Property<int>("sunrise")
                        .HasColumnType("int");

                    b.Property<int>("sunset")
                        .HasColumnType("int");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Systems");
                });

            modelBuilder.Entity("WeatherApp.Domain.Weather", b =>
                {
                    b.Property<int>("weather_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("RootId")
                        .HasColumnType("int");

                    b.Property<int>("condition")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("main")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("request_date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("weather_Id");

                    b.HasIndex("RootId");

                    b.ToTable("Weathers");
                });

            modelBuilder.Entity("WeatherApp.Domain.Wind", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("deg")
                        .HasColumnType("int");

                    b.Property<double>("speed")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Winds");
                });

            modelBuilder.Entity("WeatherApp.Domain.Root", b =>
                {
                    b.HasOne("WeatherApp.Domain.Clouds", "clouds")
                        .WithMany()
                        .HasForeignKey("cloudsId");

                    b.HasOne("WeatherApp.Domain.Coordinates", "coordinates")
                        .WithMany()
                        .HasForeignKey("coordinatesId");

                    b.HasOne("WeatherApp.Domain.Main", "main")
                        .WithMany()
                        .HasForeignKey("mainId");

                    b.HasOne("WeatherApp.Domain.System", "system")
                        .WithMany()
                        .HasForeignKey("systemId");

                    b.HasOne("WeatherApp.Domain.Wind", "wind")
                        .WithMany()
                        .HasForeignKey("windId");
                });

            modelBuilder.Entity("WeatherApp.Domain.Weather", b =>
                {
                    b.HasOne("WeatherApp.Domain.Root", null)
                        .WithMany("weather")
                        .HasForeignKey("RootId");
                });
#pragma warning restore 612, 618
        }
    }
}
